name: ðŸ“‚åˆ†æ–‡ä»¶å¤¹sync
on:
    workflow_dispatch:
jobs:
    odgd:
        name: OneDrive to Onedrive Sync ï¼ˆðŸ“‚-ï¼‰
        runs-on: ubuntu-latest
        steps:
        - name: checkout
          uses: actions/checkout@master
        - name: Download and Install rclone
          run: sudo curl https://rclone.org/install.sh | sudo bash
        - name: Decrypt config
          run: |
              bash decrypt.sh
          env:
              GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE}}
        - name: Copy
          run: |
              rclone sync onedrive-wceshi: onedrive-backup:backup --transfers 48 -v --ignore-errors
              
 odgd:
        name: OneDrive to Onedrive Sync ï¼ˆðŸ“‚-ï¼‰
        runs-on: ubuntu-latest
        steps:
        - name: checkout
          uses: actions/checkout@master
        - name: Download and Install rclone
          run: sudo curl https://rclone.org/install.sh | sudo bash
        - name: Decrypt config
          run: |
              bash decrypt.sh
          env:
              GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE}}
        - name: Copy
          run: |
              rclone sync onedrive-wceshi: onedrive-backup:backup --transfers 48 -v --ignore-errors

odgd:
        name: OneDrive to Onedrive Sync ï¼ˆðŸ“‚-ï¼‰
        runs-on: ubuntu-latest
        steps:
        - name: checkout
          uses: actions/checkout@master
        - name: Download and Install rclone
          run: sudo curl https://rclone.org/install.sh | sudo bash
        - name: Decrypt config
          run: |
              bash decrypt.sh
          env:
              GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE}}
        - name: Copy
          run: |
              rclone sync onedrive-wceshi: onedrive-backup:backup --transfers 48 -v --ignore-errors


odgd:
        name: OneDrive to Onedrive Sync ï¼ˆðŸ“‚-ï¼‰
        runs-on: ubuntu-latest
        steps:
        - name: checkout
          uses: actions/checkout@master
        - name: Download and Install rclone
          run: sudo curl https://rclone.org/install.sh | sudo bash
        - name: Decrypt config
          run: |
              bash decrypt.sh
          env:
              GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE}}
        - name: Copy
          run: |
              rclone sync onedrive-wceshi: onedrive-backup:backup --transfers 48 -v --ignore-errors



odgd:
        name: OneDrive to Onedrive Sync ï¼ˆðŸ“‚-ï¼‰
        runs-on: ubuntu-latest
        steps:
        - name: checkout
          uses: actions/checkout@master
        - name: Download and Install rclone
          run: sudo curl https://rclone.org/install.sh | sudo bash
        - name: Decrypt config
          run: |
              bash decrypt.sh
          env:
              GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE}}
        - name: Copy
          run: |
              rclone sync onedrive-wceshi: onedrive-backup:backup --transfers 48 -v --ignore-errors



odgd:
        name: OneDrive to Onedrive Sync ï¼ˆðŸ“‚-ï¼‰
        runs-on: ubuntu-latest
        steps:
        - name: checkout
          uses: actions/checkout@master
        - name: Download and Install rclone
          run: sudo curl https://rclone.org/install.sh | sudo bash
        - name: Decrypt config
          run: |
              bash decrypt.sh
          env:
              GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE}}
        - name: Copy
          run: |
              rclone sync onedrive-wceshi: onedrive-backup:backup --transfers 48 -v --ignore-errors


odgd:
        name: OneDrive to Onedrive Sync ï¼ˆðŸ“‚-ï¼‰
        runs-on: ubuntu-latest
        steps:
        - name: checkout
          uses: actions/checkout@master
        - name: Download and Install rclone
          run: sudo curl https://rclone.org/install.sh | sudo bash
        - name: Decrypt config
          run: |
              bash decrypt.sh
          env:
              GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE}}
        - name: Copy
          run: |
              rclone sync onedrive-wceshi: onedrive-backup:backup --transfers 48 -v --ignore-errors





